import React from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import logo from './logo.png';

type Category={id:number;name:string};
type Product={id:number;title:string;price:number;oldPrice:number|null;image:string|null;description?:string;category:Category};
type CartItem={product:Product;quantity:number};
const API=(import.meta.env.VITE_API_URL||'').replace(/\/$/,'');
const money=(n:number)=>new Intl.NumberFormat('uz-UZ').format(n)+' so\'m';
const tg=(window as any).Telegram?.WebApp;
function App(){
 const [tab,setTab]=React.useState('home'); const [products,setProducts]=React.useState<Product[]>([]); const [categories,setCategories]=React.useState<Category[]>([]); const [cart,setCart]=React.useState<CartItem[]>(()=>JSON.parse(localStorage.getItem('tegen_cart')||'[]')); const [search,setSearch]=React.useState(''); const [category,setCategory]=React.useState<number|null>(null); const [loading,setLoading]=React.useState(true); const [phone,setPhone]=React.useState(''); const [msg,setMsg]=React.useState('');
 React.useEffect(()=>{localStorage.setItem('tegen_cart',JSON.stringify(cart))},[cart]);
 React.useEffect(()=>{(async()=>{try{const [p,c]=await Promise.all([fetch(API+'/catalog/products'),fetch(API+'/catalog/categories')]);setProducts(await p.json());setCategories(await c.json())}catch(e){setMsg('Server bilan bog\'lanib bo\'lmadi')}finally{setLoading(false)}})()},[]);
 const filtered=products.filter(p=>(!category||p.category.id===category)&&p.title.toLowerCase().includes(search.toLowerCase()));
 const add=(p:Product)=>setCart(x=>{const old=x.find(i=>i.product.id===p.id);return old?x.map(i=>i.product.id===p.id?{...i,quantity:i.quantity+1}:i):[...x,{product:p,quantity:1}]});
 const change=(id:number,d:number)=>setCart(x=>x.map(i=>i.product.id===id?{...i,quantity:i.quantity+d}:i).filter(i=>i.quantity>0));
 const total=cart.reduce((s,i)=>s+i.product.price*i.quantity,0); const count=cart.reduce((s,i)=>s+i.quantity,0);
 async function checkout(){const u=tg?.initDataUnsafe?.user;if(!u){setMsg('Buyurtma berish uchun Telegram ichidan oching.');return} if(!phone){setMsg('Avval telefon raqamingizni kiriting.');return} const r=await fetch(API+'/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({telegramId:String(u.id),firstName:u.first_name,lastName:u.last_name,username:u.username,phone,items:cart.map(i=>({productId:i.product.id,quantity:i.quantity}))})});if(!r.ok){setMsg(await r.text());return}const o=await r.json();setCart([]);setMsg(`Buyurtma #${o.orderNumber} qabul qilindi.`);setTab('profile')}
 return <div className="app"><header className="top"><div className="brand"><img src={logo}/><div><b>TEGEN</b><span>Onlayn do'kon</span></div></div><button className="icon">♡</button></header>
 {msg&&<div className="notice" onClick={()=>setMsg('')}>{msg}</div>}
 {tab==='home'&&<><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mahsulot va toifalarni qidirish"/></div><section className="hero"><div><small>TEGEN</small><h1>Hamyonbop narxlar</h1><p>Kerakli mahsulotni tez va qulay buyurtma qiling.</p><button onClick={()=>setTab('catalog')}>Katalogni ko'rish →</button></div><div className="heroIcon">🛍️</div></section><section><div className="sectionHead"><h2>Kategoriyalar</h2><button onClick={()=>{setCategory(null);setTab('catalog')}}>Hammasi →</button></div><div className="cats">{categories.map(c=><button key={c.id} className={category===c.id?'selected':''} onClick={()=>{setCategory(c.id);setTab('catalog')}}><i>🛍️</i>{c.name}</button>)}</div></section><ProductGrid products={filtered} add={add}/></>}
 {tab==='catalog'&&<><div className="search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Mahsulot qidirish"/></div><div className="filterRow"><button className={!category?'selected':''} onClick={()=>setCategory(null)}>Hammasi</button>{categories.map(c=><button key={c.id} className={category===c.id?'selected':''} onClick={()=>setCategory(c.id)}>{c.name}</button>)}</div><ProductGrid products={filtered} add={add}/></>}
 {tab==='cart'&&<main><h2>Savat {count?`(${count})`:''}</h2>{!cart.length?<div className="empty"><div>🛒</div><p>Savat hozircha bo'sh.</p></div>:<><div className="cartList">{cart.map(i=><div className="cartItem" key={i.product.id}><div className="thumb">{i.product.image?<img src={i.product.image}/>: '🛍️'}</div><div className="cartInfo"><b>{i.product.title}</b><strong>{money(i.product.price)}</strong><div className="qty"><button onClick={()=>change(i.product.id,-1)}>−</button><span>{i.quantity}</span><button onClick={()=>change(i.product.id,1)}>+</button></div></div><b>{money(i.product.price*i.quantity)}</b></div>)}</div><div className="checkout"><h3>Jami: {money(total)}</h3><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Telefon raqami: +998..."/><button onClick={checkout}>Buyurtma berish</button></div></>}</main>}
 {tab==='profile'&&<main className="profile"><div className="avatar">👤</div><h2>Profil</h2><p>Telegram akkauntingiz buyurtmalaringiz bilan bog'lanadi.</p><input value={phone} onChange={e=>setPhone(e.target.value)} placeholder="Telefon raqami"/></main>}
 <nav><button className={tab==='home'?'active':''} onClick={()=>setTab('home')}>⌂<span>Bosh sahifa</span></button><button className={tab==='catalog'?'active':''} onClick={()=>setTab('catalog')}>⌕<span>Katalog</span></button><button className={tab==='cart'?'active':''} onClick={()=>setTab('cart')}>🛍<span>Savat {count?`(${count})`:''}</span></button><button className={tab==='profile'?'active':''} onClick={()=>setTab('profile')}>♙<span>Profil</span></button></nav></div>}
function ProductGrid({products,add}:{products:Product[];add:(p:Product)=>void}){return <section><div className="sectionHead"><h2>Mahsulotlar</h2></div>{products.length?<div className="products">{products.map(p=><article className="card" key={p.id}><div className="pic">{p.image?<img src={p.image}/>: '🛍️'}</div><h3>{p.title}</h3><strong>{money(p.price)}</strong>{p.oldPrice&&<del>{money(p.oldPrice)}</del>}<button className="add" onClick={()=>add(p)}>Savatga qo'shish</button></article>)}</div>:<div className="empty"><div>🔎</div><p>Mahsulot topilmadi.</p></div>}</section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
